# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-jupyter" do
  name "aws-jupyter"
  desc "CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-jupyter"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-jupyter"

  on_macos do
    on_intel do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Darwin_x86_64.tar.gz"
      sha256 "d2a8caa425c3ca552bf7e2e464741e4124beade590baac82c67f597ed1478d48"
    end
    on_arm do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Darwin_arm64.tar.gz"
      sha256 "be4dabb365ba420eed1b7eb8dad5d9ccf32e85b942f58e62a41bc00257759fe7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Linux_x86_64.tar.gz"
      sha256 "e4967fe796b2889fcef3c0a75670cae7ec52d062d7f3c02016eb9def00ee4d2f"
    end
    on_arm do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Linux_arm64.tar.gz"
      sha256 "a771449a71bf7512cdc8157a75e6b85e99b44732cf4921d2a33beb01f0847610"
    end
  end

  # No zap stanza required
end
