# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkcap" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "d59fa78bf3d44b47ac2366cf580f0106bea12bdd06e47a34083fe4faa5fc7b6c"
      url "https://github.com/scttfrdmn/inkcap/releases/download/v#{version}/inkcap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "13a769f71f4e1829134956735686d906887593c1735ff79f402cebf4bd36583a"
      url "https://github.com/scttfrdmn/inkcap/releases/download/v#{version}/inkcap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b50f1d8b44039ae0bfa7b55142b38c47c2148c14ecf4e7effb893212617b672b"
      url "https://github.com/scttfrdmn/inkcap/releases/download/v#{version}/inkcap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "86892896b0dea1379ad4bbde8c602982f5f2f592cf8d1a837c854906ab08a111"
      url "https://github.com/scttfrdmn/inkcap/releases/download/v#{version}/inkcap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "inkcap"
  desc "Markdown to typeset PDF in one static binary."
  homepage "https://github.com/scttfrdmn/inkcap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkcap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/inkcap"]
    end
  end

  # No zap stanza required

end
