# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkcap" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "95ba3f66aa1ea439d94c6ecba8ebd6b0919418f3035073887d138c415d1298c7"
      url "https://github.com/scttfrdmn/inkcap/releases/download/v#{version}/inkcap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c7c05e5b9d467e319323d239014e9f2e276cadf0b9edaf95cf0435f460f01c8"
      url "https://github.com/scttfrdmn/inkcap/releases/download/v#{version}/inkcap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "71cd96b31aab35fdb1ed3835e98974fbfc90c44700d241c0857e9433d8a1ba37"
      url "https://github.com/scttfrdmn/inkcap/releases/download/v#{version}/inkcap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "86246101e4956b57d0179cc5462cff322617f26e68ac49425c51e1b0d6b498c5"
      url "https://github.com/scttfrdmn/inkcap/releases/download/v#{version}/inkcap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "inkcap"
  desc "Markdown to typeset PDF in one static binary."
  homepage "https://github.com/scttfrdmn/inkcap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkcap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/inkcap"]
    end
  end

  # No zap stanza required

end
