# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsVscode < Formula
  desc "CLI tool for launching VSCode Server instances on AWS EC2 Graviton processors (Beta)"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.7.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-vscode_Darwin_x86_64.tar.gz"
      sha256 "e8236979fe8113da92327318fb218c6e1223df65ebe24cad2557baae0d25a851"

      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-vscode_Darwin_arm64.tar.gz"
      sha256 "806b53786d281866becdaab732fc9c407ac5c05d63214d6170c65662eb5d8554"

      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-vscode_Linux_x86_64.tar.gz"
      sha256 "7c5ed9dc625bd30916783fd6b2b1506ae253bbf1482e18bbfb7431610bd9130f"
      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-vscode_Linux_arm64.tar.gz"
      sha256 "3a1c073bacf503b32698a8d1da0a9fd9944c57c5610e9f0ea2383b9602dda441"
      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-vscode", "--version"
  end
end
