# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsJupyter < Formula
  desc "CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.7.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-jupyter_Darwin_x86_64.tar.gz"
      sha256 "33ea475245fb1610eadf8234347a599a35414f566f2b19a3419ae43f1f953a49"

      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-jupyter_Darwin_arm64.tar.gz"
      sha256 "de2d15fd41a9a068da906785682f74a13f7061c2332b631079db986387d43dff"

      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-jupyter_Linux_x86_64.tar.gz"
      sha256 "1fb446d283620551b7cad5be586ff5f7d374573d8357756a3b4c9fba778b27af"
      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-jupyter_Linux_arm64.tar.gz"
      sha256 "2ab8cc9d756c2ee26a6d97a7723929de49871676e43d91b8b5248845fda2ffd8"
      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-jupyter", "--version"
  end
end
