# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsRstudio < Formula
  desc "CLI tool for launching RStudio Server instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.7.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-rstudio_Darwin_x86_64.tar.gz"
      sha256 "cf8d625bf8bba15db17de38b5f61be0172d45de7de7736cc4646098bcb775d07"

      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-rstudio_Darwin_arm64.tar.gz"
      sha256 "503aff7cb301d66222e0aa35d805ce8d85296352cbc3ba1ec200d0176959bbf7"

      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-rstudio_Linux_x86_64.tar.gz"
      sha256 "11ba74fdaac05b595ada42a9bf6084ec573f89895eb63b5cabc2a9f6bbd92cf1"
      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.2/aws-rstudio_Linux_arm64.tar.gz"
      sha256 "199e918d90b384cb39f782a658cf1aaee154ef39959962c3b8bec4e1587e4d15"
      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-rstudio", "--version"
  end
end
