# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cargoship < Formula
  desc "High-performance S3 upload tool with intelligent sharding and compression"
  homepage "https://github.com/scttfrdmn/cargoship"
  version "0.35.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.35.1/cargoship_0.35.1_darwin_x86_64.tar.gz"
      sha256 "afb39988e0a084006455c6a3778fbf2acb6ae2ad0d62a59470f742cdc7a2c1ca"

      define_method(:install) do
        bin.install "cargoship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.35.1/cargoship_0.35.1_darwin_arm64.tar.gz"
      sha256 "864a361438d8a531ac216624c1bba802f9dafaafc5f85ef060a234c23a687a03"

      define_method(:install) do
        bin.install "cargoship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.35.1/cargoship_0.35.1_linux_x86_64.tar.gz"
      sha256 "a14f74f09874fc3f1cbee65e29809d5637a71e25aca90635dca00652ad53ea07"
      define_method(:install) do
        bin.install "cargoship"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.35.1/cargoship_0.35.1_linux_arm64.tar.gz"
      sha256 "2d323cd5b66f565e28132b417d10c86cd1fa14cb00e04d5e6ac436021d465652"
      define_method(:install) do
        bin.install "cargoship"
      end
    end
  end

  test do
    system "#{bin}/cargoship", "--version"
  end
end
