# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cargoship < Formula
  desc "High-performance S3 upload tool with intelligent sharding and compression"
  homepage "https://github.com/scttfrdmn/cargoship"
  version "0.30.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.30.0/cargoship_0.30.0_darwin_x86_64.tar.gz"
      sha256 "50f56083331f6c2857dc2e52a7d93c5c6c6f310ef08335f60dbe87390a6c60b2"

      define_method(:install) do
        bin.install "cargoship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.30.0/cargoship_0.30.0_darwin_arm64.tar.gz"
      sha256 "1ed9b0a36e5b8d0fce35892d8b33d98a58322755f2728a0d76dcd48974a2ba9e"

      define_method(:install) do
        bin.install "cargoship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.30.0/cargoship_0.30.0_linux_x86_64.tar.gz"
      sha256 "e85a6f8f8cbb8a92a659813d89f752d64c6ec92eccf4fbb665958ef3d9ca75e4"
      define_method(:install) do
        bin.install "cargoship"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.30.0/cargoship_0.30.0_linux_arm64.tar.gz"
      sha256 "6e9cafc74d2fc79b7303bd20cf448d58cbd8ca1897384ab33afc51d67feadb7f"
      define_method(:install) do
        bin.install "cargoship"
      end
    end
  end

  test do
    system "#{bin}/cargoship", "--version"
  end
end
