# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cicada < Formula
  desc "Fast, reliable file sync for S3"
  homepage "https://github.com/scttfrdmn/cicada"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/cicada/releases/download/v0.1.0/cicada_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "a16cfc4b0b198bf1cd458538054f9a1eaa42a1c06562eddda84cc4a1140f7ade"

      def install
        bin.install "cicada"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/cicada/releases/download/v0.1.0/cicada_0.1.0_Darwin_arm64.tar.gz"
      sha256 "bb878b73b6a9021ec944814209d4c67046a4368b8134914c446630bef05ffd70"

      def install
        bin.install "cicada"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cicada/releases/download/v0.1.0/cicada_0.1.0_Linux_x86_64.tar.gz"
      sha256 "4464ab8c2a900fd7875acd549b9ac402ebacd200ad8415bf8fe9173850c73569"
      def install
        bin.install "cicada"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cicada/releases/download/v0.1.0/cicada_0.1.0_Linux_arm64.tar.gz"
      sha256 "708c79cfea5c87072fdb8448102bc32077a043f67a22fafd291592e49ebff202"
      def install
        bin.install "cicada"
      end
    end
  end

  test do
    system "#{bin}/cicada version"
  end
end
