# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudworkstation < Formula
  desc "CLI tool for launching pre-configured cloud workstations for academic research"
  homepage "https://github.com/scttfrdmn/cloudworkstation"
  version "0.5.5"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.5/cloudworkstation_0.5.5_darwin_x86_64.tar.gz"
      sha256 "6242b69eae1968772ba46ea60e9d489c1a13a6680618287e26876e8074588988"

      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.5/cloudworkstation_0.5.5_darwin_arm64.tar.gz"
      sha256 "eb6fd3ce4800d6dbd565fdf4e580f9a229d851adb50a7cb30754d619927d3437"

      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.5/cloudworkstation_0.5.5_linux_x86_64.tar.gz"
      sha256 "f0a0a146520d5b2a21dd771b36668825ae921cbe49ae42b7eb9134b5f7c23b73"
      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.5/cloudworkstation_0.5.5_linux_arm64.tar.gz"
      sha256 "e6e24c1f851d80aa8ebc2c76e6b58ab84c286ca3c38ade5c3765ddb58da50a35"
      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
  end

  def caveats
    <<~EOS
      CloudWorkstation has been installed!

      Command Line Interface (CLI):
        cws --help

      Terminal User Interface (TUI):
        cws tui

      Quick start:
        cws templates                           # List available templates
        cws launch <template-name> <instance>   # Launch a workstation

      The daemon (cwsd) starts automatically when needed - no manual setup required!

      AWS credentials are required:
        aws configure

      Documentation: https://github.com/scttfrdmn/cloudworkstation
    EOS
  end

  test do
    system "#{bin}/cws", "--version"
    system "#{bin}/cwsd", "--version"
  end
end
