# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LensRstudio < Formula
  desc "CLI tool for launching RStudio Server instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/lens"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-rstudio_Darwin_x86_64.tar.gz"
      sha256 "0888a688a1b58644e723b49e79794836bfa23ca4392a2f02457af59bfd44448a"

      def install
        bin.install "lens-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-rstudio_Darwin_arm64.tar.gz"
      sha256 "e8f2d28627819398b31622fab6d826594354464da2a8abd51aeecf7a09b24b0b"

      def install
        bin.install "lens-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-rstudio_Linux_x86_64.tar.gz"
      sha256 "1f68190c5b5bcf0194cb2b3fd1104cf0d75a1a23aa32e7b638418b1a3222b348"
      def install
        bin.install "lens-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-rstudio_Linux_arm64.tar.gz"
      sha256 "60defdb9b9dc17c1e09a124db6cea6d7da090c162a12562bbc1293ed6e42c16b"
      def install
        bin.install "lens-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/lens-rstudio", "--version"
  end
end
