# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LensJupyter < Formula
  desc "CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/lens"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-jupyter_Darwin_x86_64.tar.gz"
      sha256 "db228008de3972f0abec2813c2bfaac5ec1b65408d15cb24b7e7e937fe8db7d0"

      def install
        bin.install "lens-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-jupyter_Darwin_arm64.tar.gz"
      sha256 "fb4d77e5e203800c8639a912e6655761414620998c89f03674f08c530f7b8228"

      def install
        bin.install "lens-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-jupyter_Linux_x86_64.tar.gz"
      sha256 "b893e681072af96196f84b1f409a00b2fe60ced1a2de00f43fc647fb6b259ef2"
      def install
        bin.install "lens-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-jupyter_Linux_arm64.tar.gz"
      sha256 "fcc9f975ff69a7e7022f75251c66da47af2bf8b595352aec82cc9efa835d7768"
      def install
        bin.install "lens-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/lens-jupyter", "--version"
  end
end
