# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LensVscode < Formula
  desc "CLI tool for launching VSCode Server instances on AWS EC2 Graviton processors (Beta)"
  homepage "https://github.com/scttfrdmn/lens"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-vscode_Darwin_x86_64.tar.gz"
      sha256 "c8f76a1371d5bb1ec9ed95b2c025206f3b20c9d4de4b6af8de7248a40dc44d32"

      def install
        bin.install "lens-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-vscode_Darwin_arm64.tar.gz"
      sha256 "139868bf7f62fc48eec9d072903415616437b94ff5e68d5e163ee796a3f80f69"

      def install
        bin.install "lens-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-vscode_Linux_x86_64.tar.gz"
      sha256 "4f9585689d83768c8697c1808003a66f71da16591192d8aaed72287ff62d0e39"
      def install
        bin.install "lens-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/lens/releases/download/v0.9.0/lens-vscode_Linux_arm64.tar.gz"
      sha256 "3904af74b033edcfa19fffa13043373e574dc533f2d0c1957648ef8d1ccd5b69"
      def install
        bin.install "lens-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/lens-vscode", "--version"
  end
end
